### ISSUE TITLE
New landing page

### ISSUE THREAD

**Issue by enmust** [geocollections/EMA#136]
Should be visually appealing and contain links to different apps

**Comment by enmust** [comment]
Card order etc

**Comment by ollehints** [comment]
Cards could be as follows:

Geokogude portaal / Geocollections of Estonia / https://geocollections.info
Geoloogiline kirjandus / Geoscience Literature Database / https://kirjandus.geoloogia.info
Geoloogiafond / Geological Reports / https://fond.egt.ee

Fossiilide portaal / Baltoscandian Fossils / https://fossiilid.info
Mineraalid ja kivimid / MInerals and Rocks / https://kivid.info
Stratigraafia ja geoloogiline ajaskaala / Stratigraphy and time scale / https://stratigraafia.info

Maardlate rakendus / Mineral Resources of Estonia / https://xgis.maaamet.ee/xgis2/page/app/maardlad
Turbageoloogia andmebaas / Peat Geology Database / https://turba.geoloogia.info
Andmerepositoorium / Geoscience Data Repository / https://doi.geocollections.info
