### ISSUE TITLE
investigate navigation

### ISSUE THREAD

**Issue by enmust** [geocollections/EMA#168]
Sometimes too much data is reloaded etc.

Header image is reloaded on some links

**Comment by ollehints** [comment]
Similar operations, click from search results tables, result hugely different downloads:
Search by 653, open drillcore and locality from results table:
Klick drillcore https://ema-dev.geoloogia.info/drillcore/3/ -- 37 requests 1.6 MB, including logos etc, some files twice
Klick locality https://ema-dev.geoloogia.info/locality/22004/ small size, 10 requests 5.5 kB, only data from API is asked

**Comment by Erikdzo** [comment]
This is happening because drillcore detail view uses the custom detail layout but locality detail view uses the default layout which is also used by the search view. Seems that switching layouts makes the application download all the files again.
