### ISSUE TITLE
Search view tabs update and additional search tables

### ISSUE THREAD

**Issue by enmust** [geocollections/EMA#171]
Take them out of table tabs. 
All of them should be visible, maybe something similar like in geokirjandus keywords

**Comment by ollehints** [comment]
User expects to find as much information as possible. Thus, in addition to localities, drillcores, samples, analysis and preparations, quick search should provide results for:
reference
specimen
stratigraphy
doi
attachment
taxon
rock

The results table links should direct to external resources:
kirjandus.geoloogia.info/reference/$id
gecollections.info/specimen/$id
stratigraafia.info/term/$id
doi.geocollections.info/10.23679/$id
gecollections.info/file/$id
fossiilid.info/$id
kivid.info/$id

Like in geocollections quick search, only tabs/buttons/tables with some results should be show (https://geocollections.info/search/%22160-5%22).
Needs to be tested if the order of "buttons" should be according to the number of results, or be constant to not confuse the user.

**Comment by ollehints** [comment]
rock is now in solr index

**Comment by enmust** [comment]
- [ ] add attachment to solr

**Comment by enmust** [comment]
Closing this, attachement imported into new issue

**Comment by enmust** [comment]
#222
