### ISSUE TITLE
Hyphen in quick search field

### ISSUE THREAD

**Issue by ollehints** [geocollections/EMA#174]
Search string often includes "-" in names, codes and numbers. We need to avoid situation where solr interprets this as operator.
Thus, if user input has "-" without preceding whitespace (for instance searching sample number **OM8-4**), the app should silently add parenthesis so that the entire input will be sent to solr as one string. If there is a space, then user likely wishes to exclude a keyword (for instance: **+martma -kaljo**).

**Comment by enmust** [comment]
This feature was already added 9057e14d2c8d8069466bed57e3574fe75f780179 but the last search update needs some optimizing because extra query parameters are put into the fast search

**Comment by Erikdzo** [comment]
Filter query parameters are also removed from quick search https://github.com/geocollections/EMA/commit/51d079c306fc00d38fb24da99d5b049b73f651a7
