### ISSUE TITLE
Improve back button

### ISSUE THREAD

**Issue by enmust** [geocollections/EMA#223]

**Comment by enmust** [comment]
replace with breadcrumbs or sth similar

**Comment by Erikdzo** [comment]
Question about how exactly breadcrumbs should work:
1. if user has breadcrumbs: **drillcores -> drillcore 1 -> locality 1** and the user presses the drillcore link in the details table. Should the outcome be **drillcores -> drillcore 1 -> locality 1 -> drillcore 1** or **drillcores -> drillcore 1** ?
2. Is it correct to assume that when user presses back button the last element should be removed from breadcrumbs i.e  **drillcores -> drillcore 1 -> locality 1** becomes **drillcores -> drillcore 1**? and when the user presses the forward button the removed element should reappear i.e **drillcores -> drillcore 1** becomes **drillcores -> drillcore 1 -> locality 1**.
3. if user has breadcrumbs: **drillcores -> drillcore 1 -> locality 1** and presses **drillcore 1** breadcrumb resulting in **drillcores -> drillcore 1** , should pressing back button go back to **drillcores** or **locality 1**?
